name: "CD: executor (pre-prod)"

on:
  push:
    branches:
      - 'deploy-executor-preprod'

jobs:
  deploy:
    uses: .github/workflows/deploy_preprod.yml@main
    with:
      build_directory: "executor"
      docker_repo_name: "backenddevelopersltd/compute-horde-executor-staging"
      dist_version_prefix: "executor-preprod"
      tag_version: "v0-preprod"
    secrets:
      dockerhub_key: ${{ secrets.DOCKERHUB_KEY }}
