name: "CD: Miner Runner (Staging)"

on:
  push:
    branches:
      - 'deploy-miner-runner-staging'

jobs:
  deploy:
    uses: .github/workflows/deploy_staging.yml@main
    with:
      build_directory: "miner/envs/runner"
      docker_repo_name: "backenddevelopersltd/compute-horde-miner-runner-staging"
      dist_version_prefix: "miner-runner-staging"
      tag_version: "v0-latest"
      build_args: "MINER_RUNNER_VERSION='${GITHUB_SHA}' MINER_IMAGE_REPO='${MINER_IMAGE_REPO}' MINER_NGINX_IMAGE_REPO='${MINER_NGINX_IMAGE_REPO}'"
    secrets:
      dockerhub_key: ${{ secrets.DOCKERHUB_KEY }}
